modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "grieflogger"
version = "${version}"
displayName = "GriefLogger"
authors = "DAQEM"
description = '''
A mod that logs griefing attempts.
'''
#logoFile = ""

[[dependencies.grieflogger]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.grieflogger]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.grieflogger]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"